[package]
name = "tuplities"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
typenum.workspace = true

[lints]
workspace = true

[features]
default = ["flatten-nest"]
alloc = []
flatten-nest = ["alloc"]
size-16 = []
size-32 = []
size-48 = []
size-64 = []
size-96 = []
size-128 = []

[[test]]
name = "flat_bridge_contracts"
required-features = ["flatten-nest"]

[[test]]
name = "flat_bridge_sizes"
required-features = ["flatten-nest"]
