[workspace]
resolver = "2"

members = ["tuplities"]

[workspace.package]
authors = ["Luca Cappelletti"]
edition = "2024"
description = "A collection of utilities for working with tuples in Rust."
license = "MIT"
repository = "https://github.com/lucacappelletti94/tuplities"
keywords = ["tuples", "utilities", "metaprogramming", "typenum"]
categories = ["development-tools", "data-structures"]
version = "0.2.0"
rust-version = "1.85"

[workspace.dependencies]
typenum = { version = "1" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "forbid"
unused_macro_rules = "forbid"
unconditional_recursion = "forbid"
unreachable_patterns = "forbid"
unused_import_braces = "forbid"
unused_must_use = "forbid"
deprecated = "deny"

[workspace.lints.clippy]
missing_errors_doc = "forbid"
missing_panics_doc = "forbid"
unnecessary_cast = "forbid"
redundant_clone = "forbid"
clone_on_copy = "forbid"
pedantic = { level = "deny", priority = -1 }
